### ISSUE TITLE
TODO: App structure file

### ISSUE THREAD

**Issue by subhog** [anticoders/readme#3]
Info: single file with routes
Info: controllers next to views
Info: Helpers object

**Comment by apendua** [comment]
@subhog In the new version of `iron-router` the routes will need to be placed in a place visible to both server and client.

**Comment by apendua** [comment]
@subhog Also, it would be nice to have some formal distinction between views and components.

**Comment by subhog** [comment]
Static files should be placed in /public/files

**Comment by apendua** [comment]
They should be also pushed to s3 during the build process and served from the cloud rather then app servers.

**Comment by subhog** [comment]
I disagree. First of all, this is a build process step, not coding convention – so it should be an issue for Nebula, not for readme.

Second, while this is generally a good idea (and I'd like it as a feature of Nebula), there are a lot of small projects / demos that will benefit more from the single-server simplicity that they would from moving files to S3.

Also, I suppose that using such moved files could be tricky, as you would need to update all links to local files in templates, csses, js code and whatever else a package decides to compile.

**Comment by apendua** [comment]
@subhog I don't consider anything packages "decide to compile" a static file. I was mainly thinking about large (>10kB) image assets.

**Comment by subhog** [comment]
I think we know what a "static file" is. Problem is (I'll be more verbose this time): if you've got a file named `/public/files/images/bgTileHuge@2x.png`, in the deployment process you move it to `//waterBucket.s3.amazonaws.com/BZYPFFFBLEH/bhTileHuge@2x.png`, then you need to change `/public/files/images/bgTileHuge@2x.png` to `//waterBucket.s3.amazonaws.com/BZYPFFFBLEH/bhTileHuge@2x.png` in every .html, .haml, .haml, .xml, .xhtml, .dhtml, .xdhtml, .jade, .css, .less, .sass, .scss, .styl, .js, .ts, .coffee, .dart, .json, .ejson, .bson, .yaml, .yml, and .etc file that contains `/public/files/images/bgTileHuge@2x.png` as a path to the `/public/files/images/bgTileHuge@2x.png` static asset. You'd also need to update `../images/bgTileHuge@2x.png` that refers to the same file from `/public/files/stylesheets/heyIvePutAStylesheetFileHereForSomeReason.less`.

:smile: 

It is late. Now I understand that probably the idea was to just not put large assets in `/public`, but move them to s3 manually and refer to them there. To which I agree, as long as we put emphasis on **large** assets. And in this case I don't see why you've said that this should be a part of the build process.

**Comment by apendua** [comment]
Actually the only problematic thing, which cannot be solved easily, are relative paths to images within "static" CSS (I assume that you put that `less` in public folder by accident, right?). But those can be safely omitted as the don't add any new value in context of Meteor environment. For any other type of situations you described, using helpers in templates and variables in compiled stylesheets can provide a sufficient level of abstraction to deal with the problem you described. One idea - for example - is to use `asset` helper, which can resolve to a file within the `public` dir in the development environment and to some s3 bucket within the production environment. Actually there's no need to use fancy / random names for folders within an s3 bucket. You can safely mimic the original directory structure from your `public` dir, so in fact it's only about adding a correct prefix.

**Comment by apendua** [comment]
Another way to deal with it would be to provide a new or modify an existing middleware on the app server to redirect http requests targeting the static assets to s3. @subhog What do you think about this one? It would eliminate all the problems you're describing.

**Comment by subhog** [comment]
@apendua  http://www.youtube.com/watch?v=RY7S6EgSlCI

**Comment by subhog** [comment]
And on a more serious note: it's sufficient to upload large assets to s3 manually when we've got some and then change respective paths using an organic brain. There's no business value in creating problems to solve.
